### ISSUE TITLE
Example application segfaults

### ISSUE THREAD

**Issue by Civil** [alekseysidorov/QtDockTile#4]
Backtrace:

<pre>
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bd4789 in QtDockManager::setMenu (this=0x7ffff7dda2e0, menu=0x7892e0) at /home/civil/projects/test/QtDockTile/lib/qtdockmanager.cpp:68
68              _providers->setMenu(menu);
(gdb) backtrace
#0  0x00007ffff7bd4789 in QtDockManager::setMenu (this=0x7ffff7dda2e0, menu=0x7892e0) at /home/civil/projects/test/QtDockTile/lib/qtdockmanager.cpp:68
#1  0x00007ffff7bd430e in QtDockTile::setMenu (this=0x773590, menu=0x7892e0) at /home/civil/projects/test/QtDockTile/lib/qtdocktile.cpp:77
#2  0x0000000000404f75 in MainWindow::MainWindow (this=0x7fffffffda40, parent=0x0) at /home/civil/projects/test/QtDockTile/example/mainwindow.cpp:38
#3  0x0000000000404d9e in main (argc=1, argv=0x7fffffffdb88) at /home/civil/projects/test/QtDockTile/example/main.cpp:31
(gdb)
</pre>

OS Info: Gentoo Linux AMD64, Qt 4.7.4, kde 4.8 RC1

**Comment by alekseysidorov** [comment]
Интересно, только совершенно не информативно. make install как в вики написано, делали?

**Comment by alekseysidorov** [comment]
Ага, так и есть. FIXED
